### ISSUE TITLE
In experiments view, show accuracy in percent

### ISSUE THREAD

**Issue by eponvert** [peoplepattern/LeVar#37]
```
Overall accuracy: 0.845
```

Should be

```
Overall accuracy: 84.5
```

for consistency with how these are displayed elsewhere.

**Comment by nickgeoca** [comment]
I have a [fix](https://github.com/nickgeoca/LeVar/commit/d34acf8a06a8294353c019e9f72b4fc165e5b331). Are you looking for 1 decimal precision? It looks like that is the precedent.
0.314159 => 31.4

**Comment by eponvert** [comment]
Awesome! Send in a pull request :100:

**Comment by eponvert** [comment]
Fix merged with #47
